### ISSUE TITLE
Adding this in Firefox.

### ISSUE THREAD

**Issue by sasonii** [tannerhodges/twitter-print-styles#20]
Can you add support for firefox?

**Comment by tannerhodges** [comment]
Hey @sasonii, definitely.

😕 I did a quick test run tonight and it looks like there are some Firefox-only bugs I'll need to work out before publishing the Firefox add-on. (For example, it fails to find the next tweet and times out on threads like https://twitter.com/adamwathan/status/1436836709145223170.)

I'm currently migrating my personal site to a new CMS, but once I'm finished with that project I can circle back to this and get it up and running (probably ≈4 weeks).

🙏 If you're able to submit a PR fixing the timeout bug in Firefox, I'll be happy to review and publish it sooner!

**Comment by tannerhodges** [comment]
Quick update: my other projects are starting to wrap up, so I should be able to start on this next week.

🙂 Thanks for your patience!

**Comment by tannerhodges** [comment]
🎉 It's live! https://addons.mozilla.org/en-US/firefox/addon/twitter-print-styles/

Let me know if you have any issues.

<a href="https://addons.mozilla.org/en-US/firefox/addon/twitter-print-styles/" target="_blank" rel="noopener"><img width="1680" alt="Screen Shot 2021-11-08 at 7 05 37 AM" src="https://user-images.githubusercontent.com/1619485/140739100-2c11f17f-c3b6-4055-a96b-2eab91272fe3.png"></a>
