### ISSUE TITLE
Twitter print styles is malfunctioning. 

### ISSUE THREAD

**Issue by Hawi0** [tannerhodges/twitter-print-styles#33]
This extension was great until couple days ago. For some reason its working properly now.
Attached two pictures deliver a clearer vision of what I am getting. Please let me know if you can help?

![1](https://github.com/tannerhodges/twitter-print-styles/assets/137734600/2c0b5bc3-04ff-4f55-b8f6-35c378534344)
![22](https://github.com/tannerhodges/twitter-print-styles/assets/137734600/a666cf0a-9248-466a-a8b7-81f1fb895903)

**Comment by Hawi0** [comment]
Its NOT working properly. Sorry it's a typo.

**Comment by millou54** [comment]
I can only second that!

> On 26 Jun 2023, at 01:52, Hawi0 ***@***.***> wrote:
> 
> 
> This extension was great until couple days ago. For some reason its working properly now.
> Attached two pictures deliver a clearer vision of what I am getting. Please let me know if you can help?
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

--

Sylvain Petitjean
Inria Nancy - Grand Est
Twitter  @Inria_Nancy   @Syl_Petitjean

**Comment by Kumarcentre** [comment]
yes this is the problem

**Comment by Mouthwash222** [comment]
Same issue here. Is the dev gone or something? Maybe it was an update to Twitter?

Can anyone verify if they *can* still use Twitter Print Styles?

**Comment by Mouthwash222** [comment]
I've tried it on my friend's computer and it still isn't working. Same message.

**Comment by tannerhodges** [comment]
🤦‍♂️ Hey all, sorry about this!

🏥  **v2.1.5** should be live now in the Chrome Web Store and fix tweets failing to load (see https://github.com/tannerhodges/twitter-print-styles/issues/33 for details).

🙏 Thanks for your patience.
