### ISSUE TITLE
Long thread - unresponsive

### ISSUE THREAD

**Issue by humanxpr** [tannerhodges/twitter-print-styles#35]
Hello there,

I'm having an issue printing to PDF a long thread, https://twitter.com/thiagoghisi/status/1604554739156258816

![image](https://github.com/tannerhodges/twitter-print-styles/assets/40764461/f31a83fb-dbb6-4ade-94d1-1fc19431e572)

Thanks for looking into it,

~G

**Comment by tannerhodges** [comment]
🏥 Fixed in https://github.com/tannerhodges/twitter-print-styles/issues/33.
