### ISSUE TITLE
Plugin not working right now.

### ISSUE THREAD

**Issue by Mouthwash222** [tannerhodges/twitter-print-styles#36]
![Screenshot](https://github.com/tannerhodges/twitter-print-styles/assets/138247332/c34fe143-21d6-4126-8c97-350917753f4c)

Unacceptable to have it not acknowledge threads for no reason I can see, and for there to be no help for it.

**Comment by Mouthwash222** [comment]
Alright! Sorry for being so rude, I was pulling my hair out yesterday (as threadreader doesn't do certain threads and readwise just happened to be not working with Twitter at the time also, due to updates, without making any kind of announcement).

**Comment by tannerhodges** [comment]
🏥 Fixed in https://github.com/tannerhodges/twitter-print-styles/issues/33.
