### ISSUE TITLE
TPT having trouble with some threads

### ISSUE THREAD

**Issue by millou54** [tannerhodges/twitter-print-styles#7]
Here are some threads I cam across that Twitter Print Styles has trouble handling (only a few out of the dozens I tested):

https://twitter.com/oliviertesquet/status/1230418133518778368
https://twitter.com/AntonioCasilli/status/1276797484732428289
https://twitter.com/jamiesusskind/status/1294169797870026752

(error message after 30 seconds)

Maybe this will help you locate a bug.

Thanks again.

**Comment by tannerhodges** [comment]
😬 I think I found a few bugs actually. I've bundled them together in https://github.com/tannerhodges/chrome-twitter-print-styles/pull/8.

For this particular issue, my best guess is that you may have hit Twitter's [rate limit](https://developer.twitter.com/en/docs/twitter-api/rate-limits)? They only allow 900 requests per 15 minutes (i.e., 1 request per second), so if you run TPS on a handful of longer threads you can hit that limit.

❓ Did you see a message like "Sorry, you are rate limited", or anything similar, when you got the 30sec timeout error?

Some other ideas: • If your account is set to a different language than English, the selector I used for timelines didn't always match. • Conflicts with another extension? • Some other Twitter settings, or Chrome settings I haven't thought of…

**Comment by millou54** [comment]
I can now print the three threads above, good! Behaviour was kind of strange though. First time I installed 2.1RC I ran into the same issue as before with 2 of the threads. Uninstalled and reinstalled, and now they all work.
Never saw the Twitter rate limit message so I don't think it played a role. Also language is set to English.

**Comment by tannerhodges** [comment]
Interesting… Sounds like I need to learn a bit more about how Chrome extensions work—seems like the button stops listening to clicks in some cases.

Glad to hear the threads are printing now, though!

I'll go ahead and submit this next release for review then, and see if I can look into the strange behavior more.

**Comment by tannerhodges** [comment]
🚀 Fixes are live in the [v2.1.0](https://github.com/tannerhodges/chrome-twitter-print-styles/releases/tag/v2.1.0) release: https://chrome.google.com/webstore/detail/twitter-print-styles/bepilablapiogeghmjiopiaoikgdcgjo

I'm going to close this issue as resolved, but let me know if you continue having the 30sec timeout or run into other issues.
